import { Hono } from "hono"

// `Env` is generated by `wrangler types` into worker-configuration.d.ts
// (globally available). Re-run that command after editing wrangler.jsonc
// bindings (R2 / D1 / KV, etc.).
const app = new Hono<{ Bindings: Env }>()

// Global safety net: never let an uncaught error crash the Worker; return
// a clean JSON error for /api/* and fall back to assets otherwise.
app.onError((err, c) => {
  console.error("worker error:", err)
  if (c.req.path.startsWith("/api/")) {
    return c.json({ ok: false, error: "internal_error" }, 500)
  }
  return c.env.ASSETS.fetch(c.req.raw)
})

// All backend routes live under /api/*.
app.get("/api/health", (c) =>
  c.json({ ok: true, service: "daviddong", time: new Date().toISOString() }),
)

// Example: return basic profile info as JSON.
// app.get("/api/hello", (c) => c.json({ hello: "world" }))

// Anything not matched by an /api route falls through to static assets
// (the React SPA). The vite plugin serves ./dist via the ASSETS binding.
app.all("*", (c) => c.env.ASSETS.fetch(c.req.raw))

export default app
